#!/bin/bash

echo "*** actualizando apt-get ***"
sudo apt-get update -y
sudo apt-get upgrade -y

echo "****** Instalar lxd ******"
sudo apt install lxd

echo "****** crear grupo ******"
newgrp lxd

echo "*** aprovisionamiento serve 1 ***"

echo "*** seteando certificado"
Certification=$(</vagrant/certificado)
echo "$Certification"

cat <<TEST> /vagrant/configuracion1.yml
config: {}
networks: []
storage_pools: []
profiles: []
cluster:
  server_name: ubuntuvm02
  enabled: true
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: ""
    description: '"source" property for storage pool "local"'
  cluster_address: 182.168.100.101:8443
  cluster_certificate: |
    $Certification
  server_address: 192.168.100.102:8443
  cluster_password: ""
  cluster_certificate_path: ""
  cluster_token: ""
TEST

echo "*** Aagregando servidor al cluster ***"

cat /vagrant/configuracion1.yml | lxd init --preseed

sleep 20

echo "*** Implementando contenedor web1 back"
sudo lxc init ubuntu:20.04 myubuntu2 --target ubuntuvm02

sleep 20

sudo lxc start myubuntu2

sleep 20

echo "*** Actualizando componentes del contenedor web1 ***"
sudo lxc exec myubuntu2 -- apt-get update
sudo lxc exec myubuntu2 -- apt-get install apache2 -y
sudo lxc exec myubuntu2 -- systemctl enable apache2

echo "*** Actualizando index.html de web1***"
sudo lxc file push /vagrant/myubuntu2/index.html myubuntu2/var/www/html/index.html

echo "*** Iniciando apache web1 ***"
sudo lxc exec myubuntu2 -- systemctl start apache2

echo "*** Fijando ip de contenedor web1 ***"
sudo lxc file push /vagrant/myubuntu2/01-netcfg.yaml myubuntu2/etc/netplan/01-netcfg.yaml
sudo lxc exec myubuntu2 -- sudo netplan apply

echo "*** servidor backup1*** "
sudo lxc init ubuntu:20.04 backup1 --target ubuntuvm02

sleep 20

sudo lxc start backup1

sleep 20

echo "*** Actualizando componentes del contenedor backup1 ***"
sudo lxc exec backup1 -- apt-get update
sudo lxc exec backup1 -- apt-get install apache2 -y
sudo lxc exec backup1 -- systemctl enable apache2

echo "*** Actualizando index.html de backup1 ***"
sudo lxc file push /vagrant/backup1/index.html backup1/var/www/html/index.html

echo "*** Iniciando apache backup1 ***"
sudo lxc exec backup1 -- systemctl start apache2

echo "Fijando ip de contenedor backup1"
sudo lxc file push /vagrant/backup1/01-netcfg.yaml backup1/etc/netplan/01-netcfg.yaml
sudo lxc exec backup1 -- sudo netplan apply