#!/bin/bash

echo "*** actualizando apt-get ***"
sudo apt-get update -y
sudo apt-get upgrade -y

echo "****** Instalar lxd ******"
sudo apt install lxd

echo "****** crear grupo ******"
newgrp lxd

echo "*** aprovisionamiento serve 1 ***"

echo "*** seteando certificado"
Certification=$(</vagrant/certificado)
echo "$Certification"

cat <<TEST> /vagrant/configuracion2.yml
config: {}
networks: []
storage_pools: []
profiles: []
cluster:
  server_name: ubuntuvm03
  enabled: true
  member_config:
  - entity: storage-pool
    name: local
    key: source
    value: ""
    description: '"source" property for storage pool "local"'
  cluster_address: 182.168.100.101:8443
  cluster_certificate: |
    $Certification
  server_address: 192.168.100.103:8443
  cluster_password: ""
  cluster_certificate_path: ""
  cluster_token: ""
TEST

echo "*** Aagregando servidor al cluster ***"

cat /vagrant/configuracion2.yml | lxd init --preseed

sleep 20

echo "*** Implementando contenedor web2"
sudo lxc init ubuntu:20.04 myubuntu3 --target ubuntuvm03

sleep 20

sudo lxc start myubuntu3

sleep 20

echo "*** Actualizando componentes del contenedor web2 ***"
sudo lxc exec myubuntu3 -- apt-get update
sudo lxc exec myubuntu3 -- apt-get install apache2 -y
sudo lxc exec myubuntu3 -- systemctl enable apache2

echo "*** Actualizando index.html de web2***"
sudo lxc file push /vagrant/myubuntu3/index.html myubuntu3/var/www/html/index.html

echo "*** Iniciando apache web2 ***"
sudo lxc exec myubuntu3 -- systemctl start apache2

echo "*** Fijando ip de contenedor web2 ***"
sudo lxc file push /vagrant/myubuntu3/01-netcfg.yaml myubuntu3/etc/netplan/01-netcfg.yaml
sudo lxc exec myubuntu3 -- sudo netplan apply

echo "*** servidor backup2*** "
sudo lxc init ubuntu:20.04 backup2 --target ubuntuvm02

sleep 20

sudo lxc start backup2

sleep 20

echo "*** Actualizando componentes del contenedor backup2 ***"
sudo lxc exec backup2 -- apt-get update
sudo lxc exec backup2 -- apt-get install apache2 -y
sudo lxc exec backup2 -- systemctl enable apache2

echo "*** Actualizando index.html de backup1 ***"
sudo lxc file push /vagrant/backup2/index.html backup2/var/www/html/index.html

echo "*** Iniciando apache backup1 ***"
sudo lxc exec backup2 -- systemctl start apache2

echo "Fijando ip de contenedor backup1"
sudo lxc file push /vagrant/backup2/01-netcfg.yaml backup2/etc/netplan/01-netcfg.yaml
sudo lxc exec backup2 -- sudo netplan apply