# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  NodeCount = 3

  (1..NodeCount).each do |i|
    config.vm.define :"ubuntuvm0#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "ubuntuvm0#{i}"
      node.vm.network :private_network, ip: "192.168.100.10#{i}"
      node.vm.provision "shell", path: "aprov_0#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "ubuntuvm0#{i}"
        v.memory = 2048
      end
    end
  end
end
